name: Run Build Script
on:
  push:
    branches: [dev, translations]
  pull_request:
    branches: [dev, translations]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: 'actions/setup-node@v1'
        with:
          node-version: '18.17.1'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
