name: Run Deployment Script
on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: 'actions/setup-node@v1'
        with:
          node-version: '18.17.1'

      - name: Install pm2
        run: npm install pm2@latest -g

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
